---
title: "Trabalho5"
author: "Thiago Tavares Lopes"
date: "2025-06-24"
output: html_document
---

```{r}

# TABELA 7.7

library(knitr)

# Criar o dataframe com os dados
dados <- data.frame(
Sexo = factor(c("Feminino", "Feminino", "Masculino", "Masculino")),
  ECG = factor(c("< 0,1 ST", "≥ 0,1 ST", "< 0,1 ST", "≥ 0,1 ST")),
  Presente = c(4, 8, 9, 21),
  Ausente = c(11, 10, 9, 6),
  Total = c(15, 18, 18, 27)
)

dados$VO <- dados$Presente / dados$Total #Valor observado de casos por categoria
format(round(dados$VO, 2), nsmall = 2)

str(dados)

# Exibir a tabela formatada
(tabela_formatada <- kable(dados, 
                          col.names = c("Sexo", "ECG", "Presente", "Ausente", "Total", "Proporção observada"), align = c("l", "l", "c", "c", "c", "c")))

# Modelo 1: Apenas intercepto
modelo1 <- glm(as.matrix(dados[,c(3,4)]) ~ 1, data = dados, family = binomial)

# Modelo 2: Intercepto e Sexo
modelo2 <- glm(as.matrix(dados[,c(3,4)]) ~ Sexo, data = dados, family = binomial)

# Modelo 3: Intercepto, Sexo e ECG
modelo3 <- glm(as.matrix(dados[,c(3,4)]) ~ Sexo + ECG, data = dados, family = binomial)

# Modelo 3: Intercepto, Sexo e ECG
modelo4 <- glm(as.matrix(dados[,c(3,4)]) ~ Sexo * ECG, data = dados, family = binomial)

summary(modelo1)
summary(modelo2)
summary(modelo3)
summary(modelo4)

(resultado_anova <- anova(modelo1, modelo2, modelo3, modelo4, test = "Chi"))

# MODELO FINAL
# EV = -1.1747 + 1.2770 * (SexoMasculino) + 1.0545 * (ECG≥ 0,1 ST)
# SexoMasculino = {0,1}
# ECG≥ 0,1 ST = {0,1}

# Modelo de regressão logística estimado (modelo3)
ggplot(dados, aes(x = Sexo, y = VO, color = ECG)) +
  geom_point(size = 4*0.75) +
  geom_smooth(method = "glm", method.args = list(family = "binomial"), se = TRUE) +
  labs(x = "Sexo", y = "Proporção observada", color = "ECG") +
  ggtitle("Modelo de Regressão Logística Estimado") +
  theme_bw() +
  theme(legend.position = c(0.1, 0.7), 
        axis.text.x = element_text(size = 13),
        legend.text = element_text(size = 13))

# Análise de resíduos do modelo final
residuos_p <- residuals(modelo3, type = "pearson")
residuos_d <- residuals(modelo3, type = "deviance")
valor_predito <- predict(modelo3, type = "response")
log_odds <- log(valor_predito / (1 - valor_predito))

dados$VO <- dados$Presente / dados$Total #Valor observado de casos por categoria
format(round(dados$VO, 2), nsmall = 2)


```



```{r}


tab7.12 <- data.frame(
"Diagnostico" = factor(c("Complicada", "Complicada", "Complicada", "Não complicada", "Não complicada", "Não complicada")),
"Tratamento" = factor(c("A", "B", "C", "A", "B", "C")),
"Sim" = c(78, 101, 68, 40, 54, 34),
"Nao" = c(28, 11, 46, 5, 5, 6),
"Total" = c(106, 112, 114, 45, 59, 40)
)

tab7.12

# Modelo 1: Apenas intercepto
modelo1 <- glm(as.matrix(tab7.12[,c(3,4)]) ~ 1, data = tab7.12, family = binomial)

# Modelo 2: Intercepto e Sexo
modelo2 <- glm(as.matrix(tab7.12[,c(3,4)]) ~ Diagnostico, data = tab7.12, family = binomial)

# Modelo 3: Intercepto, Sexo e ECG
modelo3 <- glm(as.matrix(tab7.12[,c(3,4)]) ~ Diagnostico + Tratamento, data = tab7.12, family = binomial)

# Modelo 3: Intercepto, Sexo e ECG
modelo4 <- glm(as.matrix(tab7.12[,c(3,4)]) ~ Diagnostico * Tratamento, data = tab7.12, family = binomial)

summary(modelo1)
summary(modelo2)
summary(modelo3)
summary(modelo4)

```


```{r}
tab7.18 <- data.frame(
  smk = c(0, 0, 0, 0, 1, 1, 1, 1),
  ses = c(1, 1, 0, 0, 1, 1, 0, 0),
  idade = c(0, 1, 0, 1, 0, 1, 0, 1),
  Sim = c(38, 48, 28, 40, 84, 102, 47, 59),
  Não = c(73, 86, 67, 84, 89, 46, 96, 53),
  Total = c(111, 134, 95, 124, 173, 148, 143, 112)
)

tab7.18$smk <- factor(tab7.18$smk, levels = c(0, 1), labels = c("não", "sim"))
tab7.18$ses <- factor(tab7.18$ses, levels = c(0, 1), labels = c("baixo", "alto"))
tab7.18$idade <- factor(tab7.18$idade, levels = c(0, 1), labels = c("< 40", "≥ 40"))

tab7.18

modelo1 <- glm(as.matrix(tab7.18[, c("Sim", "Não")]) ~ 1, data = tab7.18, family = binomial)
modelo2 <- glm(as.matrix(tab7.18[, c("Sim", "Não")]) ~ smk, data = tab7.18, family = binomial)
modelo3 <- glm(as.matrix(tab7.18[, c("Sim", "Não")]) ~ smk + ses, data = tab7.18, family = binomial)
modelo4 <- glm(as.matrix(tab7.18[, c("Sim", "Não")]) ~ smk + ses + idade, data = tab7.18, family = binomial)
modelo5 <- glm(as.matrix(tab7.18[, c("Sim", "Não")]) ~ smk + ses + idade + smk * ses, data = tab7.18, family = binomial)
modelo6 <- glm(as.matrix(tab7.18[, c("Sim", "Não")]) ~ smk * ses + smk * idade, data = tab7.18, family = binomial)
modelo7 <- glm(as.matrix(tab7.18[, c("Sim", "Não")]) ~ smk * ses + smk * idade + ses * idade, data = tab7.18, family = binomial)
modelo8 <- glm(as.matrix(tab7.18[, c("Sim", "Não")]) ~ smk * ses * idade, data = tab7.18,family = binomial)

# Comparação entre todos os modelos
tab7.19 <- anova(modelo1, modelo2, modelo3, modelo4, modelo5, modelo6, modelo7, modelo8, test = "Chi")
tab7.19$AIC <- c(AIC(modelo1), AIC(modelo2), AIC(modelo3), AIC(modelo4), AIC(modelo5), AIC(modelo6), AIC(modelo7), AIC(modelo8))
tab7.19

summary(modelo6)

# MODELO FINAL
# log(odds) = -0.8533 + 0.1306 * smk + 0.1852 * ses + 0.0973 * idade + 0.4859 * smk * ses + 0.7422 * smk * idade

residuos_pearson <- residuals(modelo6, type = "pearson")
residuos_deviance <- residuals(modelo6, type = "deviance")
dados_residuos <- data.frame(Residuos_Pearson = residuos_pearson, Residuos_Deviance = residuos_deviance)

# Plotando os resíduos de Pearson
ggplot(dados_residuos, aes(x = seq_along(Residuos_Pearson), y = Residuos_Pearson)) +
  geom_point(size = 4) +
  ylim(-.5, .5) +
  labs(x = "Observações", y = "Resíduos de Pearson") +
  ggtitle("Resíduos de Pearson do Modelo 6") +
  theme_bw() +
  theme(axis.text.x = element_text(size = 13),
        axis.text.y = element_text(size = 13),
        axis.title = element_text(size = 14),
        plot.title = element_text(size = 16, face = "bold"))

# Plotando os resíduos de Deviance
ggplot(dados_residuos, aes(x = seq_along(Residuos_Deviance), y = Residuos_Deviance)) +
  geom_point(size = 4) +
  ylim(-.5, .5) +
  labs(x = "Observações", y = "Resíduos Deviance") +
  ggtitle("Resíduos Deviance do Modelo 6") +
  theme_bw() +
  theme(axis.text.x = element_text(size = 13),
        axis.text.y = element_text(size = 13),
        axis.title = element_text(size = 14),
        plot.title = element_text(size = 16, face = "bold"))


# MODELO FINAL
# log(odds) = -0.8533 + 0.1306 * smk + 0.1852 * ses + 0.0973 * idade + 0.4859 * smk * ses + 0.7422 * smk * idade

# a razão de chances entre apresentar BRC quando smk = 0 (não fumante), ses = 0 (status socioeconomico alto) e idade = 0 (idade menor que 40 anos)
exp(-0.8533)

# a razão de chances entre os níveis de smk quando ses = 0 (alto) e idade = 0
exp(0.1306)

# a razão de chances entre os níveis de smk quando ses = 1 e idade = 1
exp(0.1306 + 0.4859 + 0.7422)

# a razão de chances entre os níveis de ses quando smk = 1 e idade = 1
exp(0.1852 + 0.4859 + 0.7422)
```

